# Generated by Django 3.2.9 on 2021-11-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
